declare module '*?raw' {
    const value: string;
    export = value;
}
// eslint-disable-next-line @typescript-eslint/consistent-type-definitions
interface Function {
    /** Auto-generated by TypeScript Transformer */
    readonly __implements__?: string[],
}
